language: java
jdk:
- oraclejdk8

before_deploy:
  - "mvn clean package -B -Dmaven.test.skip=true"
  - chmod +x gradlew

script:
  - ./gradlew clean build -i --continue

deploy:
  provider: releases
  api_key:
    secure: '$api_key'
  file: $(ls target/Mcmmorankup-*.jar)
  on:
    all_branches: true
    tags: true