language: java
jdk:
- oraclejdk8
dist: trusty
before_deploy:
  - "mvn clean package -B -Dmaven.test.skip=true"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: '$api_key'
  file: target/Mcmmorankup-0.8.0.jar
  skip_cleanup: true
  on:
    all_branches: true