language: java
jdk:
- oraclejdk8

before_deploy:
  - "mvn clean package -B -Dmaven.test.skip=true"
  - export FOO=$(ls target/Mcmmorankup-*.jar)

deploy:
  provider: releases
  api_key:
    secure: '$api_key'
  file: "${FOO}"