language: java
jdk:
- oraclejdk8

before_deploy:
  - "mvn clean package -B -Dmaven.test.skip=true"
  - git tag "v0.8.0"

deploy:
  provider: releases
  api_key:
    secure: '$api_key'
  file: "target/Mcmmorankup-*.jar"
  skip_cleanup: true
  on:
    all_branches: true