language: java
jdk:
- openjdk8

before_deploy:
  - "mvn clean package -B -Dmaven.test.skip=true"
  - export FOO=$(ls target/Mcmmorankup-*.jar)
  
deploy:
  provider: releases
  api_key:
    secure: 5F4TAjX3V1m51EHtzPxorQ
  file: "${FOO}"