name: Mcmmorankup
main: me.stutiguias.mcmmorankup.Mcmmorankup
version: 0.6.1
author: Stutiguias, zrocweb
depend: [Vault,mcMMO]
commands:
  mru:
   description: RankUp in your skills
   usage:
   
permissions:
    mru.hability:
       description: Gives access to provide player option to choose ability skill
       default: true
    mru.reload:
       description: reload the plugin
       default: op
